package com.example.hideaway.navigation

const val HOME_URL = "home"
const val SIGNUP_URL = "signup"
const val LOGIN_URL = "login"
const val SPLASH_URL = "splash"
const val MOOD_URL = "mood"
const val CHAT_URL = "chat"
const val STRENGTHS_URL = "strengths"
const val GRATITUDE_URL = "gratitude"
const val THOUGHT_URL = "thought"
const val SAFETY_URL = "safety"
const val ADD_PATIENTS_URL = "add_products"
const val VIEW_PATIENTS_URL = "view_products"
const val MENU_URL = "menu"
const val CHOICE_URL = "choice"
const val CONTACT_URL = "contact"
const val STRATEGIES_URL = "strategy"
const val WARNINGS_URL = "warnings"
const val OTHER_URL = "other"
